kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: {{ocp-namespace}}
  name: run-as-user-route
  labels:
    app: run-as-user
spec:
  to:
    kind: Service
    name: run-as-user-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
